### PR TITLE
Uh, it was not supposed to work before this fix...

### PR DESCRIPTION
**Pull request by LeiRoF**
Relative import that was not supposed to work but don't ask me why, it work ... sometimes

### CODE REVIEW

**Review by Aeris1One — APPROVED** [review]
LGTM, such little hotfixes should be merged right away without waiting for review imo

**Comment by Aeris1One** [comment]
Should we merge ?

**Comment by LeiRoF** [comment]
Lot of things happens since last time we were active so I will test this PR tonight to ensure it work correctly

**Comment by LeiRoF** [comment]
Ok, nevermind, we let the project with a beta branch only 1 commit behind the last edits, cool ^^

**Comment by LeiRoF** [comment]
Test and approved

**Pull request merged**
